ignoreWorkspaceRootCheck: true
shamefullyHoist: true
strictPeerDependencies: false
autoInstallPeers: true
shellEmulator: true

packages:
  - playground
ignoredBuiltDependencies:
  - esbuild
onlyBuiltDependencies:
  - sharp
